Description: Create VPC and associated infrastructure to test networking concepts.

AWSTemplateFormatVersion: '2010-09-09'

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'false'
      EnableDnsHostnames: 'false'
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: mobvpc

  VpcFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      DeliverLogsPermissionArn: arn:aws:iam::144363914423:role/flowlogsRole
      LogGroupName: CloudTrail/DefaultLogGroup
      ResourceId: { "Ref" : "VPC" }
      ResourceType: VPC
      TrafficType: ALL
